export interface PlayerStats {
  name: string;
  university: string;
  season: string;
  points: number;
  rebounds: number;
  assists: number;
  blocks: number;
  steals: number;
  fieldGoalPct: number;
  freeThrowPct: number;
  minutesPlayed: number;
  games: number;
  turnovers: number;
}

export interface SimilarPlayer extends PlayerStats {
  similarityScore: number;
  draftPick: number;
  draftYear: number;
  draftTeam: string;
}

export interface RadarDimension {
  dimension: string;
  label: string;
}

export const MICHIGAN_GOLD = "#FFCB05";
export const MICHIGAN_BLUE = "#00274C";

export const radarDimensions: RadarDimension[] = [
  { dimension: "scoring", label: "Anotación" },
  { dimension: "rebounding", label: "Rebotes" },
  { dimension: "rimProtection", label: "Protección de aro" },
  { dimension: "efficiency", label: "Eficiencia" },
  { dimension: "playmaking", label: "Creación de juego" },
];

export const adayMara: PlayerStats = {
  name: "Aday Mara",
  university: "Michigan",
  season: "2025-26",
  points: 11.1,
  rebounds: 6.9,
  assists: 2.4,
  blocks: 2.6,
  steals: 0.4,
  fieldGoalPct: 66.7,
  freeThrowPct: 50.9,
  minutesPlayed: 22.5,
  games: 28,
  turnovers: 1.9,
};

const RADAR_RANGES = {
  scoring: { min: 5, max: 20 },
  rebounding: { min: 3, max: 12 },
  rimProtection: { min: 0.5, max: 4 },
  efficiency: { min: 40, max: 72 },
  playmaking: { min: 0.3, max: 4 },
};

function clamp(value: number, min: number, max: number) {
  return Math.max(min, Math.min(max, value));
}

export function computeRadar(player: PlayerStats): Record<string, number> {
  return {
    scoring: Math.round(((clamp(player.points, RADAR_RANGES.scoring.min, RADAR_RANGES.scoring.max) - RADAR_RANGES.scoring.min) / (RADAR_RANGES.scoring.max - RADAR_RANGES.scoring.min)) * 100),
    rebounding: Math.round(((clamp(player.rebounds, RADAR_RANGES.rebounding.min, RADAR_RANGES.rebounding.max) - RADAR_RANGES.rebounding.min) / (RADAR_RANGES.rebounding.max - RADAR_RANGES.rebounding.min)) * 100),
    rimProtection: Math.round(((clamp(player.blocks, RADAR_RANGES.rimProtection.min, RADAR_RANGES.rimProtection.max) - RADAR_RANGES.rimProtection.min) / (RADAR_RANGES.rimProtection.max - RADAR_RANGES.rimProtection.min)) * 100),
    efficiency: Math.round(((clamp(player.fieldGoalPct, RADAR_RANGES.efficiency.min, RADAR_RANGES.efficiency.max) - RADAR_RANGES.efficiency.min) / (RADAR_RANGES.efficiency.max - RADAR_RANGES.efficiency.min)) * 100),
    playmaking: Math.round(((clamp(player.assists, RADAR_RANGES.playmaking.min, RADAR_RANGES.playmaking.max) - RADAR_RANGES.playmaking.min) / (RADAR_RANGES.playmaking.max - RADAR_RANGES.playmaking.min)) * 100),
  };
}

export const similarPlayers: SimilarPlayer[] = [
  {
    name: "A.J. Hammons",
    university: "Purdue",
    season: "2014-15",
    similarityScore: 93.9,
    draftPick: 46,
    draftYear: 2016,
    draftTeam: "Dallas Mavericks",
    points: 11.9,
    rebounds: 6.7,
    assists: 0.9,
    blocks: 2.8,
    steals: 0.5,
    fieldGoalPct: 54.0,
    freeThrowPct: 66.9,
    minutesPlayed: 24.3,
    games: 34,
    turnovers: 1.5,
  },
  {
    name: "Christian Koloko",
    university: "Arizona",
    season: "2021-22",
    similarityScore: 93.8,
    draftPick: 33,
    draftYear: 2022,
    draftTeam: "Toronto Raptors",
    points: 12.6,
    rebounds: 7.3,
    assists: 1.4,
    blocks: 2.8,
    steals: 0.8,
    fieldGoalPct: 63.5,
    freeThrowPct: 73.5,
    minutesPlayed: 25.4,
    games: 37,
    turnovers: 1.4,
  },
  {
    name: "Karl-Anthony Towns",
    university: "Kentucky",
    season: "2014-15",
    similarityScore: 93.8,
    draftPick: 1,
    draftYear: 2015,
    draftTeam: "Minnesota Timberwolves",
    points: 10.3,
    rebounds: 6.7,
    assists: 1.1,
    blocks: 2.3,
    steals: 0.5,
    fieldGoalPct: 56.6,
    freeThrowPct: 81.3,
    minutesPlayed: 21.1,
    games: 39,
    turnovers: 1.0,
  },
  {
    name: "Amari Williams",
    university: "Drexel",
    season: "2021-22",
    similarityScore: 93.6,
    draftPick: 46,
    draftYear: 2025,
    draftTeam: "Orlando Magic",
    points: 9.5,
    rebounds: 7.3,
    assists: 1.1,
    blocks: 2.0,
    steals: 0.6,
    fieldGoalPct: 52.1,
    freeThrowPct: 63.2,
    minutesPlayed: 20.6,
    games: 28,
    turnovers: 1.3,
  },
  {
    name: "Trevor Booker",
    university: "Clemson",
    season: "2007-08",
    similarityScore: 93.4,
    draftPick: 23,
    draftYear: 2010,
    draftTeam: "Minnesota Timberwolves",
    points: 11.0,
    rebounds: 7.3,
    assists: 1.5,
    blocks: 1.9,
    steals: 0.7,
    fieldGoalPct: 55.5,
    freeThrowPct: 57.3,
    minutesPlayed: 26.6,
    games: 34,
    turnovers: 1.6,
  },
];

export const extendedSimilarPlayers: SimilarPlayer[] = [
  {
    name: "David Lee",
    university: "Florida",
    season: "2002-03",
    similarityScore: 93.2,
    draftPick: 30,
    draftYear: 2005,
    draftTeam: "New York Knicks",
    points: 11.2,
    rebounds: 6.8,
    assists: 1.9,
    blocks: 1.4,
    steals: 0.7,
    fieldGoalPct: 64.8,
    freeThrowPct: 62.4,
    minutesPlayed: 26.2,
    games: 33,
    turnovers: 1.6,
  },
  {
    name: "Roy Hibbert",
    university: "Georgetown",
    season: "2007-08",
    similarityScore: 93.1,
    draftPick: 17,
    draftYear: 2008,
    draftTeam: "Indiana Pacers",
    points: 13.3,
    rebounds: 6.3,
    assists: 1.9,
    blocks: 2.2,
    steals: 0.5,
    fieldGoalPct: 60.9,
    freeThrowPct: 64.6,
    minutesPlayed: 26.3,
    games: 34,
    turnovers: 1.8,
  },
  {
    name: "Patrick O'Bryant",
    university: "Bradley",
    season: "2004-05",
    similarityScore: 93.0,
    draftPick: 9,
    draftYear: 2006,
    draftTeam: "Golden State Warriors",
    points: 10.0,
    rebounds: 7.4,
    assists: 0.6,
    blocks: 2.8,
    steals: 0.9,
    fieldGoalPct: 55.7,
    freeThrowPct: 70.1,
    minutesPlayed: 23.1,
    games: 27,
    turnovers: 1.3,
  },
  {
    name: "Al Horford",
    university: "Florida",
    season: "2005-06",
    similarityScore: 92.9,
    draftPick: 3,
    draftYear: 2007,
    draftTeam: "Atlanta Hawks",
    points: 11.3,
    rebounds: 7.6,
    assists: 2.0,
    blocks: 1.7,
    steals: 1.0,
    fieldGoalPct: 60.8,
    freeThrowPct: 61.1,
    minutesPlayed: 25.9,
    games: 39,
    turnovers: 1.5,
  },
  {
    name: "Daniel Gafford",
    university: "Arkansas",
    season: "2017-18",
    similarityScore: 92.7,
    draftPick: 38,
    draftYear: 2019,
    draftTeam: "Chicago Bulls",
    points: 11.8,
    rebounds: 6.2,
    assists: 0.7,
    blocks: 2.2,
    steals: 0.5,
    fieldGoalPct: 60.5,
    freeThrowPct: 52.8,
    minutesPlayed: 22.6,
    games: 35,
    turnovers: 1.4,
  },
  {
    name: "Donovan Clingan",
    university: "UConn",
    season: "2023-24",
    similarityScore: 92.5,
    draftPick: 7,
    draftYear: 2024,
    draftTeam: "Portland Trail Blazers",
    points: 13.0,
    rebounds: 7.4,
    assists: 1.5,
    blocks: 2.5,
    steals: 0.5,
    fieldGoalPct: 63.9,
    freeThrowPct: 58.3,
    minutesPlayed: 22.5,
    games: 35,
    turnovers: 1.5,
  },
  {
    name: "Robert Williams",
    university: "Texas A&M",
    season: "2016-17",
    similarityScore: 92.4,
    draftPick: 27,
    draftYear: 2018,
    draftTeam: "Boston Celtics",
    points: 11.9,
    rebounds: 8.2,
    assists: 1.4,
    blocks: 2.5,
    steals: 0.7,
    fieldGoalPct: 55.8,
    freeThrowPct: 59.0,
    minutesPlayed: 25.8,
    games: 31,
    turnovers: 1.8,
  },
  {
    name: "Alex Len",
    university: "Maryland",
    season: "2012-13",
    similarityScore: 92.3,
    draftPick: 5,
    draftYear: 2013,
    draftTeam: "Phoenix Suns",
    points: 11.9,
    rebounds: 7.8,
    assists: 1.0,
    blocks: 2.0,
    steals: 0.2,
    fieldGoalPct: 53.4,
    freeThrowPct: 68.6,
    minutesPlayed: 26.4,
    games: 38,
    turnovers: 1.6,
  },
  {
    name: "Jalen Duren",
    university: "Memphis",
    season: "2021-22",
    similarityScore: 92.3,
    draftPick: 13,
    draftYear: 2022,
    draftTeam: "Charlotte Hornets",
    points: 12.0,
    rebounds: 8.1,
    assists: 1.3,
    blocks: 2.1,
    steals: 0.8,
    fieldGoalPct: 59.7,
    freeThrowPct: 62.5,
    minutesPlayed: 25.3,
    games: 29,
    turnovers: 2.5,
  },
  {
    name: "Neemias Queta",
    university: "Utah State",
    season: "2018-19",
    similarityScore: 92.5,
    draftPick: 39,
    draftYear: 2021,
    draftTeam: "Sacramento Kings",
    points: 11.8,
    rebounds: 8.9,
    assists: 1.6,
    blocks: 2.4,
    steals: 0.7,
    fieldGoalPct: 61.4,
    freeThrowPct: 56.5,
    minutesPlayed: 27.1,
    games: 35,
    turnovers: 1.7,
  },
];

export const allComparablePlayers: SimilarPlayer[] = [
  ...similarPlayers,
  ...extendedSimilarPlayers,
];

export const statColumns = [
  { key: "points", label: "PTS" },
  { key: "rebounds", label: "REB" },
  { key: "assists", label: "AST" },
  { key: "blocks", label: "BLK" },
  { key: "fieldGoalPct", label: "FG%" },
  { key: "freeThrowPct", label: "FT%" },
  { key: "minutesPlayed", label: "MIN" },
  { key: "steals", label: "STL" },
  { key: "turnovers", label: "TO" },
] as const;
